// <auto-generated />
using System;
using Maripiell.Services.CouponAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maripiell.Services.CouponAPI.Migrations
{
    [DbContext(typeof(CouponDBContext))]
    partial class CouponDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Maripiell.Services.CouponAPI.Domain.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3935),
                            DiscountAmount = 0.10000000000000001,
                            IsDeleted = false,
                            MinAmount = 5000,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3943)
                        },
                        new
                        {
                            Id = 2,
                            Code = "20OFF",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3948),
                            DiscountAmount = 0.20000000000000001,
                            IsDeleted = false,
                            MinAmount = 10000,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3948)
                        },
                        new
                        {
                            Id = 3,
                            Code = "30OFF",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3949),
                            DiscountAmount = 0.29999999999999999,
                            IsDeleted = false,
                            MinAmount = 15000,
                            UpdatedBy = 1,
                            UpdatedDate = new DateTime(2024, 1, 17, 20, 46, 35, 233, DateTimeKind.Local).AddTicks(3950)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
